### ISSUE TITLE
Problem with Spaces 

### ISSUE THREAD

**Issue by Clamsy1111** [mets11rap/guildlink#4]
Hy. How can i find a Room what have Spaces in It’s Name?

Or How can i search for User? I tried so much, but it wont work.

|find user 4445

No User Found

And Here is the Same with spaces. What i have to do?

**Comment by exoRift** [comment]
Hi! You don't find rooms. You either create one, join one, or get invited to one.
As for finding users, the user must be in a mutual guild with the bot to be found.

I hope this helped! 😊

**Comment by Clamsy1111** [comment]
No, sorry

yes, that’s what i mean with finding the Room. I can’t join the Room „ dieser ist mein Raum „ 

I enter: |join dieser ist mein Raum 1234

room not found

i tried:
|join "dieser ist mein Raum" 1234
|join 'dieser ist mein Raum' 1234
|join dieser-ist-mein-Raum 1234
|join dieseristmeinRaum 1234
|join dieser%20ist%20mein%20Raum 1234

nothing helps

That is the same to find user with spaces, i can’t find them… OK, i shoul try this again tomorrow. But i can’t find myself for example

|find clamsy 3229

user not found

i tried:
|find clamsy #3229
|find clamsy3229
|find clamsy#3229

nothing works, and there are no spaces in the name. what have i to do, if there are spaces in the name?

So, i have to go to bed now. it’s very late in Germany ;-) Nice Greetings

Hope i hear from you tomorrow

Clamsy

**Comment by exoRift** [comment]
Sorry to hear about your issues.

As for the room issue, looking at the database, it seems you're putting in the wrong name for the room as well as the wrong password. I can't tell you the room name because that would violate privacy and security, but your best bet is to type `|room` in the server that owns the room to view its information (You must be authorized to in that server).
Remember, the command is `|join NAME PASSWORD`

As for the `find` command issue, you may be putting in the wrong name, the wrong capitalization, or you're putting in the user's nickname instead of their username.
![find](https://i.imgur.com/l7VrCry.png)

I hope you get this sorted out!

###### I'm closing the issue because I believe I have solved your problem. If something is still wrong, please reopen the issue rather than make a new one.

**Comment by Clamsy1111** [comment]
Find User Issue:

It is NOT working with Spaces in the Name. I found myself clamsy, and another user with just one-part-name.

But here: No chance



One-Word-Names are working:
For Example


And the room-name was an example. thats right. i never send a password via mail…



You see, i named it correct, but it won’t work. And the password is also correct.

Can you help me now?

It’s a Problem with the Spaces in Names and Rooms.

**Comment by exoRift** [comment]
Hm, it must be the way the arguments are parsed. I'll have this fixed as soon as possible.

**Comment by Clamsy1111** [comment]
Thank you ;-)


M. A.
clamsy1111@gmail.com

**Comment by exoRift** [comment]
Hi, I just wanted to give you a little update.

The fix for the `find` command and the `join` command are both implemented. However, Before I push this update to GuildLink's master branch, I'd like to install the latest version of Cyclone, the framework the bot runs on which I am the creator of. I have a few changes planned for Cyclone's next version that are not finished, so I don't want to update GuildLink only to finish Cyclone's next update after.

Besides for the time it'll take to finish these features, I'm also a bit busy due to some projects and a high priority commission, so these fixes may take a bit to get released. I'm sorry about the delays. I'll try to get this out as soon as possible.

**Comment by Clamsy1111** [comment]
OK, no matter.

Take your time, and give me a response please, when finished…

Thanks a lot

M. A.
clamsy1111@gmail.com

**Comment by Clamsy1111** [comment]
Hy, sorry, i have to disturb you again…

I tested your Bot with two servers, it work so far so good. OK, now today i want to invite it to my official server…

The Bot is online. but |room will not open…

i make an other server name „meister“ i invite de Bot. and |room works… But not at my server..

Why not? What is the problem with it

**Comment by exoRift** [comment]
To initiate the room, you must be the owner of the server. Get the owner to initiate it, and then have him set a management role.

**Comment by Clamsy1111** [comment]
OK, i’m just a Admin, not the owner….

**Comment by Clamsy1111** [comment]
That is really bad now.

Our server owner is rarely online. Now I can not do anything? I can not even do something about an invitation.

And the server owner does not know enough about discord and bots.

What can I do there? I already have many bots on the server - for gaming. but this one really depends on the role of owner?

**Comment by exoRift** [comment]
I'm sorry, but for the server's sake, only the owner can set up or join a room. You need him to initiate it and then add your Admin role as a management role in the room panel.
